ALTER TABLE "address_tag" DROP CONSTRAINT "address_tag_address_unique";--> statement-breakpoint
ALTER TABLE "address_tag" ADD COLUMN "transaction_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "transaction" ADD COLUMN "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (sequence name "transaction_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "transaction" ADD COLUMN "hash" text PRIMARY KEY NOT NULL;--> statement-breakpoint
ALTER TABLE "transaction" ADD COLUMN "from" text NOT NULL;--> statement-breakpoint
ALTER TABLE "transaction" ADD COLUMN "to" text;--> statement-breakpoint
ALTER TABLE "transaction" ADD COLUMN "value" text NOT NULL;--> statement-breakpoint
ALTER TABLE "transaction" ADD COLUMN "blockNumber" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "transaction" ADD COLUMN "timestamp" timestamp NOT NULL;--> statement-breakpoint
ALTER TABLE "transaction" ADD COLUMN "type" text NOT NULL;--> statement-breakpoint
ALTER TABLE "transaction" ADD COLUMN "wallet_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "address_tag" ADD CONSTRAINT "address_tag_transaction_id_transaction_id_fk" FOREIGN KEY ("transaction_id") REFERENCES "public"."transaction"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transaction" ADD CONSTRAINT "transaction_wallet_id_wallet_id_fk" FOREIGN KEY ("wallet_id") REFERENCES "public"."wallet"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "address_tag" DROP COLUMN "address";--> statement-breakpoint
ALTER TABLE "address_tag" DROP COLUMN "createdAt";--> statement-breakpoint
ALTER TABLE "address_tag" DROP COLUMN "updatedAt";--> statement-breakpoint
ALTER TABLE "transaction" ADD CONSTRAINT "transaction_hash_unique" UNIQUE("hash");